FROM    golang:1.13-alpine

RUN     apk add -U python py-pip python-dev musl-dev gcc git bash
RUN     pip install pre-commit

COPY    --from=golangci/golangci-lint:v1.24.0 /usr/bin/golangci-lint /usr/bin/golangci-lint

WORKDIR /go/src/github.com/dnephin/dobi
COPY    .pre-commit-config.yaml ./
RUN     git init && pre-commit install-hooks

ENV     CGO_ENABLED=0
CMD     ["pre-commit", "run", "-a", "-v"]
