
FROM    docker/compose:1.8.0

RUN     apk add -U bash git curl
ENV     USER user

RUN     export VERSION=1.12.1; \
        curl -Ls https://get.docker.com/builds/Linux/x86_64/docker-$VERSION.tgz | \
        tar -xz docker/docker && \
        mv docker/docker /usr/local/bin/ && \
        rmdir docker
