#!/bin/bash
set -eu

gitsha=$(git rev-parse --short HEAD)
builddate="$(date)"

osarchlist=${DOBI_BUILD_OSARCH:="linux/amd64 linux/arm linux/arm64 darwin/amd64 windows/amd64"}

gox \
    -ldflags "-X github.com/dnephin/dobi/cmd.gitsha=$gitsha \
              -X \"github.com/dnephin/dobi/cmd.buildDate=$builddate\"" \
    -output='/go/bin/dobi-{{.OS}}{{if ne .Arch "amd64"}}-{{.Arch}}{{end}}' \
    -osarch="$osarchlist" .

if [[ -e /go/bin/dobi-linux ]]; then
    echo "linking dobi to dobi-linux"
    ln -sf dobi-linux /go/bin/dobi || true
fi
