#!/bin/bash
set -eu

gitsha=$(git rev-parse --short HEAD)
builddate="$(date)"
gox \
    -ldflags "-X github.com/dnephin/dobi/cmd.gitsha=$gitsha \
              -X \"github.com/dnephin/dobi/cmd.buildDate=$builddate\"" \
    -output="/go/bin/dobi-{{.OS}}" \
    -arch="amd64" -os="darwin linux windows" \
    .
