#!/bin/bash

set -eu

. script/run-dind

docker images

docker build -t dobi-dev -f dockerfiles/Dockerfile.build .
docker run \
    -v $PWD:/go/src/github.com/dnephin/dobi \
    -v $PWD/circle:/go/bin \
    dobi-dev \
    bash -ec "glide install; go install"

./circle/dobi linter
./circle/dobi docs-img
