#!/bin/bash
set -eu -o pipefail

dobi="/go/bin/dobi-linux"

function test_example {
    local example="$1"
    pushd "$example"

    $dobi test | tee output
    bash -ex -o pipefail assertions

    # Cleanup, skip it on circleci because it struggles with removing things
    if [[ -n "${CIRCLE_BRANCH:-}" ]]; then
        $dobi autoclean
    fi
    rm -f output

    popd
}

if [[ "$DOBI_EXAMPLE" != "" ]]; then
    test_example $DOBI_EXAMPLE
    exit
fi

for example in examples/*; do
    test_example $example
done
