#!/bin/bash

exec filewatcher \
    -x '.git' \
    -x '.dobi' \
    -x '.glide' \
    -x 'vendor' \
    -x '**/*.swp' \
    -x 'dist' \
    -x 'script' \
    -x 'docs' \
    -- \
    go test -v './${dir}'
