#!/bin/bash
exec filewatcher \
    -e create -e write \
    -x 'dist' \
    -x 'dockerfiles' \
    -x 'docs' \
    -x 'examples' \
    -x 'script' \
    -x 'vendor' \
    -x '_results' \
    -x '**/*___jb_tmp___' \
    -x '**/*___jb_old___' \
    -- \
    go test -v -timeout 10s './${dir}'
